name: Generate changelog
on:
  push:
    branches: [ main ]
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "✏️ Generate release changelog"
      uses: heinrichreimer/github-changelog-generator-action@v2.3
      