on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  generate-release-notes:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Release Drafter
          uses: release-drafter/release-drafter@v5.21.1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
  create-github-release:
    name: Create GitHub Release
    needs: generate-release-notes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
